# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(644, 178)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pB_download = QtWidgets.QPushButton(self.centralwidget)
        self.pB_download.setGeometry(QtCore.QRect(20, 90, 161, 61))
        self.pB_download.setObjectName("pB_download")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 131, 31))
        self.label.setObjectName("label")
        self.lE_link = QtWidgets.QLineEdit(self.centralwidget)
        self.lE_link.setGeometry(QtCore.QRect(120, 40, 451, 31))
        self.lE_link.setObjectName("lE_link")
        self.r_playlst = QtWidgets.QRadioButton(self.centralwidget)
        self.r_playlst.setGeometry(QtCore.QRect(410, 90, 161, 21))
        self.r_playlst.setObjectName("r_playlst")
        self.r_vdeo = QtWidgets.QRadioButton(self.centralwidget)
        self.r_vdeo.setGeometry(QtCore.QRect(410, 110, 151, 21))
        self.r_vdeo.setObjectName("r_vdeo")
        self.l_status = QtWidgets.QLabel(self.centralwidget)
        self.l_status.setGeometry(QtCore.QRect(200, 100, 161, 51))
        self.l_status.setObjectName("l_status")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pB_download.setText(_translate("MainWindow", "Download"))
        self.label.setText(_translate("MainWindow", "YouTube Link :"))
        self.r_playlst.setText(_translate("MainWindow", "Play List Download"))
        self.r_vdeo.setText(_translate("MainWindow", "Video Download"))
        self.l_status.setText(_translate("MainWindow", "Ready"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
